### ISSUE TITLE
cinnamon-menu-editor cut button does not function as expected

### ISSUE THREAD

**Issue by hopelessdecoy** [linuxmint/cinnamon-menus#68] opened 2023-12-29 15:20 UTC
If you go into the cinnamon-menu-editor program to modify your launch menu and cut an application into another category it will seem to work (the cut icon disappears in original category and pastes into the new one) but going back to the old category it will have reappeared. The expected behavior is that the application will be moved not copied. Deleting the original will delete both, losing the entry completely.

![image](https://github.com/linuxmint/cinnamon-menus/assets/9456373/0a20d436-e8d6-429f-861c-8539f41d034a)

System:
Kernel: 5.15.0-88-generic x86_64 bits: 64
compiler: gcc v: 11.4.0
Desktop: Cinnamon 5.8.4
tk: GTK 3.24.33
wm: muffin
dm: LightDM
Distro: Linux Mint 21.2
Victoria base: Ubuntu 22.04 jammy
Processes: 408
Init: systemd v: 249

**Comment by rcalixte** [comment] 2023-12-29 16:11
The cinnamon repository is the right place for this. Closing as a duplicate of linuxmint/cinnamon#11998

**Closed by rcalixte** 2023-12-29 16:11 UTC
